spring:
  application:
    name: omni-backend

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/omni_db
    username: omni_user
    password: omni_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Flyway will handle schema creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  elasticsearch:
    uris: http://${ES_HOST:localhost}:9200

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: omnistorenf@gmail.com
    password: ihen atrx stzr urob
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

jwt:
  secret: YmFzZTY0LWVuY29kZWQtc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMyeWJ0ZXMtbG9uZw== # Example base64 key
  expiration: 86400000 # 1 day in ms
  refresh-expiration: 604800000 # 7 days in ms

server:
  port: 8080

app:
  storefront-url: ${STOREFRONT_URL:http://localhost:3000}

ghn:
  api:
    url: https://online-gateway.ghn.vn/shiip/public-api/v2
    token: ${GHN_TOKEN:f7e341a6-5f45-11f1-a694-7a6b2378a77f}
    shopId: 6471542

vnpay:
  tmn-code: UD2YB7G7
  hash-secret: DJ8X3REITF7WMJQ5HGIJKNKKTSO8YQDK
